/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;




import com.jtattoo.plaf.noire.NoireLookAndFeel;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UnsupportedLookAndFeelException;

import java.util.ArrayList;

import Processes.Process;

/**
 *
 * @author prabath s
 */
public class gui2 extends JFrame {

    /**
     * Creates new form gui2
     */
    
    Box vbox;
    
    JTextField t;
    int jobNo;
    int k;
    int st,at,iat,idt;
    int serviceTime;
    ArrayList<Process> processList=new ArrayList<Process>(); // Array list to store processes(jobs)
    int index = 0;// counter for process index
    
    public gui2() {
        
        vbox = Box.createVerticalBox();
        vbox.setSize(30,30);
        jobNo=1;
        k=1;
        serviceTime=0;
        initComponents();
        wrningLbl.setVisible(false);
        //jPanel1.add(new JTextField());
         pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jobLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        AddBtn = new javax.swing.JButton();
        ATime = new javax.swing.JTextField();
        STime = new javax.swing.JTextField();
        IATime = new javax.swing.JTextField();
        IDTime = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        wrningLbl = new javax.swing.JLabel();
        timeSlice = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(725, 349));
        setResizable(false);

        jobLbl.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jobLbl.setText("Job 1:");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/labels/At.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/labels/ST .png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/labels/IRT .png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/labels/IDT.png"))); // NOI18N

        AddBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/labels/Add_new.png"))); // NOI18N
        AddBtn.setMaximumSize(new java.awt.Dimension(90, 40));
        AddBtn.setMinimumSize(new java.awt.Dimension(90, 40));
        AddBtn.setPreferredSize(new java.awt.Dimension(90, 40));
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });

        STime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STimeActionPerformed(evt);
            }
        });

        IATime.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                IATimeFocusGained(evt);
            }
        });
        IATime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IATimeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IATimeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IATimeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IATimeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                IATimeMouseReleased(evt);
            }
        });
        IATime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IATimeActionPerformed(evt);
            }
        });

        IDTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTimeActionPerformed(evt);
            }
        });

        TA.setEditable(false);
        TA.setColumns(20);
        TA.setRows(5);
        TA.setMargin(new java.awt.Insets(5, 2, 2, 2));
        jScrollPane1.setViewportView(TA);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/labels/Schedule_new.png"))); // NOI18N
        jButton2.setMaximumSize(new java.awt.Dimension(90, 40));
        jButton2.setMinimumSize(new java.awt.Dimension(90, 40));
        jButton2.setPreferredSize(new java.awt.Dimension(90, 40));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        wrningLbl.setForeground(new java.awt.Color(255, 0, 0));
        wrningLbl.setText("<html>This time <br> ");

        timeSlice.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26" }));
        timeSlice.setMaximumSize(new java.awt.Dimension(20, 20));
        timeSlice.setMinimumSize(new java.awt.Dimension(20, 20));
        timeSlice.setPreferredSize(new java.awt.Dimension(20, 20));

        jLabel6.setText("<html>Time Slice: <br> (In seconds)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jobLbl)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ATime))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(STime))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wrningLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(IATime))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IDTime, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(timeSlice, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jobLbl)
                            .addComponent(ATime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(STime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IATime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wrningLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeSlice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(109, 109, 109)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTimeActionPerformed

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
        try {
            if(!ATime.getText().equals("")){Integer.parseInt(ATime.getText());}
            if(!STime.getText().equals("")){Integer.parseInt(STime.getText());}
            if(!IATime.getText().equals("")){Integer.parseInt(IATime.getText());}
            if(!IDTime.getText().equals("")){Integer.parseInt(IDTime.getText());};
            
            
        } catch (Exception e) {
            k=0;
            JOptionPane.showMessageDialog(rootPane, "Inputs should be integers");
        }
        if(k==1){
            if(ATime.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Arrival Time Should Be Given!");
            }
        
            else if(STime.getText().equals("")){
            
                JOptionPane.showMessageDialog(this, "Service Time Should Be Given!");
            }
            else if (IATime.getText().equals("") && !IDTime.getText().equals("") ){
                System.out.println("in");
                JOptionPane.showMessageDialog(this, "I/O Arrival Time Should Be Given!");
            }
            
           else if (!IATime.getText().equals("") && IDTime.getText().equals("") ){
                System.out.println("in");
                JOptionPane.showMessageDialog(this, "I/O Duration Time Should Be Given!");
            }
           else if(serviceTime+Integer.parseInt(STime.getText())>25){
               JOptionPane.showMessageDialog(this, "Total service time should be less than\n 25 seconds");
           }
            
            else{
                
               if (jobNo<=5){
        
                TA.append("Job"+jobNo+"\t  "+ATime.getText()+"\t"+"    "+"    "+"    "+STime.getText()+"\t"+"    "+"    "+"    "+IATime.getText()+"\t"+"    "+"    "+"    "+IDTime.getText()+"\n\n");
                jobNo++;
                if(jobNo<6){
                jobLbl.setText("Job "+String.valueOf(jobNo)+":");
                }
                st=Integer.parseInt(STime.getText());//
                at=Integer.parseInt(ATime.getText());//
                
                if(!IATime.getText().equals("")){
                    iat=Integer.parseInt(IATime.getText());//
                    idt=Integer.parseInt(IDTime.getText());//
                    processList.add(new Process(at, st, 4,index,iat,idt));
                    index++;
                }
                
                //malith's code starts
                //
                else{
                processList.add(new Process(at, st, 4,index));
                index++;
                }
                //
                serviceTime=serviceTime+st;
                ATime.setText(null);
                STime.setText(null);
                IATime.setText(null);
                IDTime.setText(null);
               }
               else if(jobNo>5){
                   JOptionPane.showMessageDialog(this, "Only 5 tasks are allowed");
               }
            }
        }
        k=1;
        
        
              
    }//GEN-LAST:event_AddBtnActionPerformed

    private void STimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_STimeActionPerformed

    private void IATimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IATimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IATimeActionPerformed

    private void IATimeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IATimeMouseEntered
        // TODO add your handling code here:
        wrningLbl.setVisible(true);
        
    }//GEN-LAST:event_IATimeMouseEntered

    private void IATimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IATimeMouseClicked
        // TODO add your handling code here:
        wrningLbl.setVisible(true);
    }//GEN-LAST:event_IATimeMouseClicked

    private void IATimeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IATimeMouseExited
        // TODO add your handling code here:
        wrningLbl.setVisible(false);
    }//GEN-LAST:event_IATimeMouseExited

    private void IATimeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IATimeMouseReleased
        // TODO add your handling code here:
        System.out.println("released");
       // wrningLbl.setVisible(false);
    }//GEN-LAST:event_IATimeMouseReleased

    private void IATimeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IATimeMousePressed
        // TODO add your handling code here:
        System.out.println("pressed");
        wrningLbl.setVisible(true);
    }//GEN-LAST:event_IATimeMousePressed

    private void IATimeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IATimeFocusGained
        // TODO add your handling code here:
         System.out.println("focus");
         wrningLbl.setVisible(true);
    }//GEN-LAST:event_IATimeFocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        OSGUI osgui = new OSGUI(processList,1); // create OSGUI form and set visible
        this.setVisible(false);
        osgui.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        try {
            /* Create and display the form */
            javax.swing.UIManager.setLookAndFeel(new NoireLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(gui2.class.getName()).log(Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ATime;
    private javax.swing.JButton AddBtn;
    private javax.swing.JTextField IATime;
    private javax.swing.JTextField IDTime;
    private javax.swing.JTextField STime;
    private javax.swing.JTextArea TA;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jobLbl;
    private javax.swing.JComboBox timeSlice;
    private javax.swing.JLabel wrningLbl;
    // End of variables declaration//GEN-END:variables
}
